### PR TITLE
Issue 379 added check for null before converting envVars to HashMap

### PR DESCRIPTION
**Pull request by ifel**
Added validation envVars variable before attempting to convert TreeMap to HashMap.

### CODE REVIEW

**Comment by carpnick** [comment]
So the code [here](https://github.com/opscode-cookbooks/jenkins/blob/v2.2.2/libraries/slave.rb#L334) used to set it to null.

Now you get the thing you need with the HashMap if it is not null.  So it appears this return null now, like previous release.

Should we return an empty HashMap in this case, or return null like you are doing?

**Comment by ifel** [comment]
Well, the problem was, in [groovy.json.JsonBuilder](https://github.com/opscode-cookbooks/jenkins/blob/v2.2.2/libraries/slave.rb#L353) constructor, if the list passed to the constructor contains a TreeMap element, it fails with NPE, but if parses HashMap without problems. That's why I convert TreeMap to HashMap.

I had env vars set and it failed.

So, before my previous change, it had been returning null if there were no environment variables configured, and instance of [EnvVars class] (http://javadoc.jenkins-ci.org/hudson/EnvVars.html) which is in fact [java.util.TreeMap<String,String>](http://docs.oracle.com/javase/7/docs/api/java/util/TreeMap.html?is-external=true) if there were env vars.

In this change, it returns null if there are no env vars, and EnvVars converted to HashMap if there are env vars.

Therefore, this change reverts old behavior (return null) for slaves wo env vars, and keeps fix for slaves with env vars.

**Comment by carpnick** [comment]
Ok sounds good to me :+1:

**Comment by schisamo** [comment]
This looks great. Thanks for the contribution @ifel!

**Pull request merged**
