### PR TITLE
plugins: Do a better job understanding "latest" version

### PR DESCRIPTION
**Pull request by docwhat**
This copies the "desired_version" code and uses it in more
places so that we can accurately figure out if the version is
up-to-date.

This should fix some problems with plugins not updating.

I couldn't figure out how to represent this in a test of any kind.  If you have a suggestion, please tell me!

### CODE REVIEW

**Comment by docwhat** [comment]
ping? Any comments?

**Comment by docwhat** [comment]
@schisamo or @ksubrama -- Any comments?

**Comment by jtimberman** [comment]
@opscode-cookbooks/ociv Please review.

**Comment by schisamo** [comment]
This was merged as 4b52c6f835d1e972330ce160a4e430aae20f78ac.

**Pull request closed without merging**
