### PR TITLE
Added support for jvm_options on slave_ssh resource

### PR DESCRIPTION
**Pull request by simao**
This adds support for a new `java_path` option when using the `slave` resource, analagous to the `jvm_options` option.

### CODE REVIEW

**Comment by jtimberman** [comment]
This is a duplicate of #304.

**Comment by simao** [comment]
Like I commented there, it's actually not a duplicate. Can you reopen?

**Comment by chef-supermarket** [comment]
Hi. I am an automated pull request bot named Curry. There are commits in this pull request whose authors are not yet authorized to contribute to Chef Software, Inc. projects or are using a non-GitHub verified email address. To become authorized to contribute, you will need to sign the Contributor License Agreement (CLA) as an individual or on behalf of your company. [You can read more on Chef's blog.](https://www.chef.io/blog/2014/06/23/changes-to-the-contributor-license-agreement-process)

## GitHub Users Who Are Not Authorized To Contribute

The following GitHub users do not appear to have signed a CLA:

* @simao

[Please sign the CLA here.](https://supermarket.chef.io/become-a-contributor)

**Comment by jtimberman** [comment]
Sure, thanks! You'll need to sign the CLA per the curry bot comment above, though.

**Comment by schisamo** [comment]
This was merged as 9aa18d6a58bf8427082ed1acef0692bba5ea517e.

**Comment by chef-supermarket** [comment]
Hi. Your friendly Curry bot here. Just letting you know that all commit authors have become authorized to contribute. I have added the "Signed CLA" label to this issue so it can easily be found in the future.

**Pull request closed without merging**
