### PR TITLE
Support username/password for cli

### LINKED ISSUE #299: Support --username and --password as parameters to jenkins-cli.jar
When security is enabled, and realm is set to UNIX user/group database, it is impossible to use the jenkins cookbook with a UNIX user. This is because private key authentication is disabled, which in turn is due to [JENKINS-22346](https://issues.jenkins-ci.org/browse/JENKINS-22346).

The `jenkins-cli.jar` utility accepts the parameters `--username` and `--password`, which enables the use of a UNIX user again. This functionality is, sadly, not supported by the cookbook.

I kindly ask that you implement this feature, either as parameters to the resources, or similar to the private key variable in `node.run_state[:jenkins_private_key]`.

### PR DESCRIPTION
**Pull request by simao**
This should fix #299

### CODE REVIEW

**Comment by johnbellone** [comment]
:+1:

**Comment by adrianmoisey** [comment]
It would be super rad if this got merged

**Comment by jtimberman** [comment]
@opscode-cookbooks/ociv Please review.

**Comment by simao** [comment]
Actually I messed up the PR, but there are 2 separate issues with 2 separate PR, I just messed up the branch names. Will fix ASAP

**Comment by simao** [comment]
Ok, created new PR with fixed banching. sorry about that.

**Pull request closed without merging**
