### PR TITLE
Windows Slaves Logon As A Service right automatically add

### PR DESCRIPTION
**Pull request by carpnick**
Added a new xml element to winsw here: https://github.com/kohsuke/winsw/pull/70

It has been since released in winsw 1.17.  Would address #374 
/cc @mcallb

### CODE REVIEW

**Comment by stephenlauck** [comment]
I would like to :+1:  this if it's a real blocker, but would also like it if @carpnick could give me a little more context on what this could affect. @mtyler Do you know how I would test this?

**Comment by stephenlauck** [comment]
@someara Are you also able to review a PR like this?

**Comment by carpnick** [comment]
@stephenlauck @someara , This involves adding the [Logon As A Service](https://technet.microsoft.com/en-us/library/cc957141.aspx) right to the configured user of the WIndows Service.  By default, even the Administrator account is not in this group.  So basically if you have a Windows Slave not on a domain, where GPO could push this setting down,  you have no way to assign the user this logon right.  
Basically without this change, the jenkins_windows_slave resource will configure the winsw configuration correctly, but the service will not start.  This is because the user was not added to the logon as a service security group.

Integrated into [winsw 1.17](https://github.com/kohsuke/winsw/compare/1.16...winsw-1.17), is the new logic to add the right automatically for the specified user in the winsw configuration file with this config change.

**Comment by mtyler** [comment]
I :+1: this change

**Comment by someara** [comment]
LGTM... @schisamo ?

**Comment by schisamo** [comment]
This was merged to master as:
https://github.com/opscode-cookbooks/jenkins/commit/1448725fbdbc5d7e599dc9c7d1abcaaff026767f
https://github.com/opscode-cookbooks/jenkins/commit/1afca1ecafe8034cd20eb1f02dfbe492c4047923

**Pull request closed without merging**
